In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("Social_Network_Ads.csv")
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
data.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
User ID            400 non-null int64
Gender             400 non-null object
Age                400 non-null int64
EstimatedSalary    400 non-null int64
Purchased          400 non-null int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [5]:
x = data[['EstimatedSalary',"Age"]].values
y = data['Purchased'].values

In [6]:
#x = x.reshape(len(x),1)

In [7]:
np.unique(y,return_counts=True)

(array([0, 1], dtype=int64), array([257, 143], dtype=int64))

In [8]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.85,random_state=0)

In [9]:
xtrain

array([[ 18000,     32],
       [ 42000,     60],
       [ 76000,     19],
       [ 99000,     36],
       [ 26000,     19],
       [ 83000,     60],
       [ 89000,     24],
       [ 58000,     27],
       [ 47000,     40],
       [ 70000,     42],
       [150000,     32],
       [ 77000,     35],
       [ 63000,     22],
       [ 22000,     45],
       [ 89000,     27],
       [ 82000,     18],
       [ 79000,     42],
       [ 60000,     40],
       [ 34000,     53],
       [107000,     47],
       [144000,     58],
       [ 83000,     59],
       [ 55000,     24],
       [ 35000,     26],
       [ 38000,     58],
       [ 80000,     42],
       [ 75000,     40],
       [130000,     59],
       [ 41000,     46],
       [ 60000,     41],
       [ 64000,     42],
       [146000,     37],
       [ 48000,     23],
       [ 33000,     25],
       [ 84000,     24],
       [ 96000,     27],
       [ 63000,     23],
       [ 33000,     48],
       [ 90000,     48],
       [104000,     42],


In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtrain =  sc.fit_transform(xtrain)
xtest =  sc.transform(xtest)

In [11]:
xtrain

array([[-1.5099209 , -0.58252386],
       [-0.81097862,  2.09652308],
       [ 0.17918961, -1.82636709],
       [ 0.8490093 , -0.19980287],
       [-1.27694014, -1.82636709],
       [ 0.38304778,  2.09652308],
       [ 0.55778335, -1.34796585],
       [-0.3450171 , -1.0609251 ],
       [-0.66536564,  0.18291812],
       [ 0.00445404,  0.37427862],
       [ 2.33426165, -0.58252386],
       [ 0.20831221, -0.29548312],
       [-0.19940412, -1.53932634],
       [-1.39343052,  0.66131936],
       [ 0.55778335, -1.0609251 ],
       [ 0.35392518, -1.92204733],
       [ 0.2665574 ,  0.37427862],
       [-0.28677191,  0.18291812],
       [-1.04395938,  1.42676134],
       [ 1.08199006,  0.85267986],
       [ 2.15952608,  1.90516258],
       [ 0.38304778,  2.00084283],
       [-0.43238488, -1.34796585],
       [-1.01483678, -1.15660535],
       [-0.927469  ,  1.90516258],
       [ 0.29567999,  0.37427862],
       [ 0.15006702,  0.18291812],
       [ 1.75180975,  2.00084283],
       [-0.84010121,

In [12]:
np.unique(ytrain,return_counts=True)

(array([0, 1], dtype=int64), array([212, 128], dtype=int64))

In [13]:
### Build Model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [14]:
### Train the model
model.fit(xtrain,ytrain)

C:\Users\ARPIT  GUPTA\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [15]:
### Prediction
ypred = model.predict(xtest)

In [16]:
ytest

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0], dtype=int64)

In [17]:
ypred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

In [18]:
from sklearn.metrics import accuracy_score
accu = accuracy_score(ytest,ypred)
accu

0.9333333333333333

In [19]:
np.unique(ytest,return_counts=True)

(array([0, 1], dtype=int64), array([45, 15], dtype=int64))

In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest,ypred)
cm

array([[44,  1],
       [ 3, 12]], dtype=int64)