In [ ]:
import numpy as np

In [ ]:
x = np.array([[0,1,0],[0,0,1],[1,1,0],[1,0,1]])  ## input
y = np.array([[1],[0],[1],[0]])  ## actual output

In [ ]:
x

array([[0, 1, 0],
       [0, 0, 1],
       [1, 1, 0],
       [1, 0, 1]])

In [ ]:
## Define Weights
np.random.seed(10)
weights = np.random.random((3,1))
weights

array([[0.77132064],
       [0.02075195],
       [0.63364823]])

In [ ]:
## Neuron Mathematical Equation
sum = 0.02 + np.dot(x,weights)
sum

array([[0.04075195],
       [0.65364823],
       [0.81207259],
       [1.42496888]])

In [ ]:
### Activation Function (Sigmoid)
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [ ]:
ypred = sigmoid(sum)
ypred

array([[0.51018658],
       [0.65783211],
       [0.69255099],
       [0.8061162 ]])

In [ ]:
ypred.round()

array([[1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
sum = 0.02 + np.dot(x,weights)
ypred = sigmoid(sum)
error = y - ypred
error

array([[ 0.48981342],
       [-0.65783211],
       [ 0.30744901],
       [-0.8061162 ]])

In [ ]:
### Function for Gradient Descent
def gradient(a,x):
  return a * x * (1-x)

In [ ]:
sum = 0.02 + np.dot(x,weights)
ypred = sigmoid(sum)
error = y - ypred
change_in_weight = gradient(error,ypred)
weights = weights+np.dot(x.T,change_in_weight)
error

array([[ 0.48981342],
       [-0.65783211],
       [ 0.30744901],
       [-0.8061162 ]])

In [ ]:
### Training
for i in range(1000):
  sum = 0.02 + np.dot(x,weights)
  ypred = sigmoid(sum)
  error = y - ypred
  change_in_weight = gradient(error,ypred)
  weights = weights+np.dot(x.T,change_in_weight)

In [ ]:
error

array([[ 0.01661719],
       [-0.01604776],
       [ 0.01621209],
       [-0.01644883]])

In [ ]:
ypred.round()

array([[1.],
       [0.],
       [1.],
       [0.]])

In [ ]:
weights

array([[ 0.02508472],
       [ 4.06109077],
       [-4.13652734]])